### ISSUE TITLE
Structure document along attribute type

### ISSUE THREAD

**Issue by marcvs** [aarc-community/architecture-guidelines#1]
Types that we could consider include:
- Identifier                                                                                                                  
- Name                                                                
- E-Mail                                                              
- Domain of home-org                                                  
- Affiliation in community                                                 
- Affiliation at home-org                                                  
- Assurance                                                           
- Entitlement
- Capabilities
- Supplemental Name Information

**Comment by NicolasLiampotis** [comment]
The document structure has been revised as follows:

* Subject Identifiers
  * Public Subject Identifier
  * Pairwise Subject Identifier
* Name
  * Display Name
  * Given Name
  * Family Name
 * Email
   * Email address
   * Email verification status 
 * Organisation
   * Organisation Domain
   * Organisation's Country
   * Organisation compliance with policies
  * Affiliation
    * Affiliation within Home Organisation
    * Affiliation within Community/Research Infrastructure
  * Assurance
  * Group and Role information
  * Resource Capabilities 
  * External Subject Identifiers
    * ORCID 
  * SSH Public Keys
  * Certificates
  * Subject Type
  * User agreement to policies
  * Identity/account status
  * User's authentication authorities

**Comment by NicolasLiampotis** [comment]
Updated structure:

* Subject Identifier
  * Public Subject Identifier
  * Pairwise Subject Identifier
* Name
  * Display Name
  * Given Name
  * Family Name
* Email
  * Email Address
  * Email verification status
* Organisation	
  * Organisation Display Name 
  * Organisation Domain
  * Organisation’s Country
  * Organisation compliance with policies
* Affiliation
  * Affiliation within Home Organisation
  * Affiliation within Community/Research Infrastructure
* Assurance
* Group and Role information	
* Resource Capabilities
* External Subject Identifiers
  * External subject identifiers
  * ORCID
* SSH Public keys
* Certificates
  * Certificate Subject DNs
  * Certificate Issuer DNs
* Subject Type
* Subject Status
* Agreement to Policies
* Authenticating Authorities

**Comment by NicolasLiampotis** [comment]
Agreed on new structure with the addition of Organisation Display Name
