### ISSUE TITLE
Clarify Terminology: Trust Anchors vs. Trust Authorities

### ISSUE THREAD

**Issue by NicolasLiampotis** [aarc-community/architecture-guidelines#12]
The information document on Establishing trust between OAuth 2 proxies [[AARC-I058](https://docs.google.com/document/d/18bvC63O3wti8nw5lhgUbBVMtDG9ggqpe5ad8Om9voBo/edit)] currently  uses "Trust Authority" which seems interchangeable with "Trust Anchor" from the OpenID Federation specification [[OID-Fed](https://openid.net/specs/openid-connect-federation-1_0-29.html)]. However, there's a distinction between these roles in the context of [[OID-Fed](https://openid.net/specs/openid-connect-federation-1_0-29.html)]:

* Trust Anchor: The root of trust in the federation.
* Intermediate Entity: An entity within the trust chain that issues statements about subordinate entities (other intermediate entities or leaf entities).

There are two options to address this terminology inconsistency in AARC-I058:

1. **Align with current OID-Fed Terminology:** Revise AARC-I058 to use "Trust Anchor" and "Intermediate Entity" consistently 
2. **Add "Trust Authority" definition:**  Extend Section 1.2 with new term. We could also consider proposing the new term upstream. There is a definition of "Trust Authority" in https://www.rfc-editor.org/rfc/rfc5217.txt:

> "Trust Authority: An entity that manages a Trust List for use by one or more relying parties."

**Comment by baszoetekouw** [comment]
Discussed in the Architecture Meeting this afternoon; decoded to add the defintion of "Trust Authority" to the document and make clear that it should not confused with the OIDC "Trust Anchor" (although the implementation of a Trust Authority might be an OIDC Trust Anchor).

**Comment by NicolasLiampotis** [comment]
Added Trust Authority definition to the terms section

**Comment by dianagudu** [comment]
Re-opening the issue because it is still unclear what the difference between Trust Anchor and Trust Authority is.

**Comment by NicolasLiampotis** [comment]
The definition has been updated:

A Trust Authority is a third party which is trusted to identify entities.
 - In OpenID Federation, a Trust Authority is a third party represented by one or more [Trust Anchors](https://openid.net/specs/openid-federation-1_0.html#name-trust-chain).
 - In IGTF, a Trust Authority is a Certification Authority; the Trust Anchors are its root or intermediate certificates in the IGTF distribution.
 - A Trust Authority could simply maintain and publish a list of identifiers of entities, provided the association between each entity and its identifier can be checked by other trusted means
