### ISSUE TITLE
Clarify Trust Authority model in federation

### ISSUE THREAD

**Issue by NicolasLiampotis** [aarc-community/architecture-guidelines#13]
The current informational document on Establishing trust between OAuth2 proxies [[AARC-I058](https://docs.google.com/document/d/18bvC63O3wti8nw5lhgUbBVMtDG9ggqpe5ad8Om9voBo/edit)] mentions "Trust Authorities" (plural), while the diagrams depict a single Trust Authority, potentially creating confusion regarding the supported number of Trust Authorities. 

The diagrams can continue to depict only a single Trust Authority, however the text should be revised to explicitly state that this is for simplicity, while the trust evaluation methods allow for more.

**Comment by baszoetekouw** [comment]
Discussed in the architecture call.  Text was clarified to say while only a single TA is depicted for simplicity, multiple are supported.
