### ISSUE TITLE
Release of core attributes whose values are not available

### ISSUE THREAD

**Issue by NicolasLiampotis** [aarc-community/architecture-guidelines#19]
The question is whether we should release an attribute with a value that denotes that it is empty (e.g. empty or “” or “---”) or we do not release the attribute at all.

The REFEDS Personalized Access attribute profile says that if an attribute does not have a value then it may not be released at all.

We need some guidance here.

**Comment by NicolasLiampotis** [comment]
According to the [OpenID Connect Core Specification, Section 5.3.2](https://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse):

> If a Claim is not returned, that Claim Name SHOULD be omitted from the JSON object representing the Claims; it SHOULD NOT be present with a null or empty string value.

**Comment by c00kiemon5ter** [comment]
I totally agree with this :)

**Comment by NicolasLiampotis** [comment]
After reviewing the relevant specifications, we have decided that when the attribute/claim value is not available, the attribute/claim will not be released. This decision is supported by the following points:

1. **[REFEDS Personalized Entity Category](https://refeds.org/category/personalized)**: 

> It is recognized that not every subject can be associated with values for every attribute. [...] In such cases, it is expected that those attribute(s) may not be provided. The obligation to release these attributes is general and not subject-specific.

2. **[OpenID Connect Core specification](https://openid.net/specs/openid-connect-core-1_0.html)**:

> If a claim is not returned, the claim name SHOULD be omitted from the JSON object representing the claims; it SHOULD NOT be present with a null or empty string value.

This approach ensures compliance with both the REFEDS Personalized Entity Category and OpenID Connect specifications.
