### ISSUE TITLE
Refresh flows seems te be more general than described 

### ISSUE THREAD

**Issue by baszoetekouw** [aarc-community/architecture-guidelines#21]
(AARC-G073)

The refresh flow seems more generally usable than just for the specific case between and infra proxy and Community AAI. This is not made clear in the text and diagrams though.

Could we rephrase the document to describe a general situation (using terms like, for example, "OAuth proxy" and "Autorisation service") and use the specific BPA-situation with infra proxies and community AAI as a specific example or implementation?

**Comment by NicolasLiampotis** [comment]
The text and diagrams have been updated to describe a general scenario using "OAuth Proxy A" and "OAuth Proxy B," with the specific case of infra proxies and Community AAI as an example.

**Comment by NicolasLiampotis** [comment]
Closing this issue now as the changes have been accepted in the document. Feel free to reopen if there are any further adjustments needed.
