### ISSUE TITLE
Given Name is single-valued in SCIM

### ISSUE THREAD

**Issue by marcvs** [aarc-community/architecture-guidelines#3]
Other that `oidc` and `saml`, scim only supports a single value in the givenName.
urn:ietf:params:scim:schemas:core:2.0:User:name.middleName seems to be the place where additional givenNames can be placed.

1) Is this ok with us?
2) What about LDAP?

**Comment by marcvs** [comment]
LDAP: GivenName is a mutlivalued  attribute of strings

For the document: Implementation instructions should be put into the document

**Comment by marcvs** [comment]
The higher level recommendation is to user
- either [`givenName` + `familyName`] (and potentially all the extras to overcome SCIM's single valuedness)
- or [displayName] (which I hope is even recommended)

We could add a note in the document to recommend `displayName` and use a space separated list of names in both `givenName` and `familyName`

**Comment by msalle** [comment]
But that doesn't work in several places which use [familyName + givenName] ? (https://en.wikipedia.org/wiki/Personal_name#Eastern_name_order)

**Comment by marcvs** [comment]
I cecked rfc6350 (vcf, https://datatracker.ietf.org/doc/html/rfc6350#section-6.2.2). That seems to work well with many names, since it is around for a while.

Essentially they have multiple values (comma separated) for each of the name fields:
- Family Names
- Given Names
- Additional Names
- Honorific Prefixes
- Honorific Suffixes

SCIM defines these exact name fields, but it does not have that "comma separated multi-value" feature. Actually, the SCIM spec says nothing about this at all. Not a single example, not in the spec, nothing found on google.

I'm checking with Peter G., who has a good connection to SCIM folks.

**Comment by msalle** [comment]
Might also be worth checking with our SURF colleagues who use [SCIM for e.g. SRAM](https://servicedesk.surf.nl/wiki/display/WIKI/Connect+a+service+to+SCIM) (their AARC-BPA proxy for researchers in the NL). More specifically this nice overview with the different protocols: https://servicedesk.surf.nl/wiki/display/WIKI/Attributes+in+SRAM

**Comment by marcvs** [comment]
I've checked with Peter Gietz, who told me that this is a non-issue. The attribute itself is single valued, meaning that there is just one attribute. It may however contain multiple values, separated in non specified ways. SCIM wants to be simpler than LDAP and therefore is not super strict.

The example he gives for familyName illustrates this: `"Schmidt-Mayer"` and `"Li Peng"` are valid values.
Using `givenName="Karl Peter"`  or `givenName = "Karl"` and `middleName = "Peter"` is apparently both valid.
