### ISSUE TITLE
Email: How to deal with multi-valuedness

### ISSUE THREAD

**Issue by marcvs** [aarc-community/architecture-guidelines#5]
"email" is single valued in some and mutli-valued in other protocols.

The way out is probably to identify a preferred email address in the Communityh AAI

**Comment by marcvs** [comment]
Move this as a comment to the SCIM implementation

**Comment by c00kiemon5ter** [comment]
In practice, we have seen services fail when receiving multiple email addresses for users.

Are we really adding any value when providing multiple email addresses?

**Comment by msalle** [comment]
Question is how to translate from one protocol to another: if you receive two in an unordered list, how do you decide which one to keep? Also (but less strong argument) I could imagine people might want to specify a backup/recovery email address?

**Comment by c00kiemon5ter** [comment]
> if you receive two in an unordered list, how do you decide which one to keep?

That's a hard question.
One possible way out of this is to ask the user to select the value (everytime? for this session? for all? it is unclear).

> specify a backup/recovery email address

This cannot be deducted from a multi-valued attribute. This would require its own attribute that signals the type of usage.

**Comment by marcvs** [comment]
Just an idea: email addresses are comma separated. Why not simply concatenate them with a comma?

**Comment by msalle** [comment]
> Just an idea: email addresses are comma separated. Why not simply concatenate them with a comma?

sounds like a great idea since it's ordered. Only problem might be that outlook uses `;` as separator apparently, but that seems to go against https://www.rfc-editor.org/rfc/rfc5322 as far as I can tell and might have been relaxed nowadays.
So just use the RFC5322 format?

**Comment by NicolasLiampotis** [comment]
### Question:
**Are multivalued email addresses useful?**

### Answer: 
Within an AARC BPA based environment, we should have one email address for contact purposes. If there is a reason for more than one email address (e.g. for different purposes, like primary and backup email) then most probably they should be conveyed with different claims/attributes that make the purpose/use of that email clear. 
Having said this, _an AARC BPA compliant proxy should be able to handle receiving multiple emails in the email attribute (SAML) and not fail._ In this case they should have a process for selecting one of the emails as the contact email of the user. This means that AARC BPA Proxy should release one value in the `mail` attribute and `email` claim.

### Further discussion 
The discussion continued about the relationship between emails and identities and for example that a Google email is a Google identity. We should have a way to be able to say that this is a Google identity or that I need the Google identity of a user. This is not related with the email discussion in this issue, but rather with the linking feature and we need to come back to this. Probably we need a list of key-value pairs and a new issue to track this discussion.

### Next steps
- Update Email attribute definition in G056
- A **new issue** should be opened to track the discussion regarding identity linking and requesting identities from specific providers.

**Comment by NicolasLiampotis** [comment]
Updated [attribute definition](https://docs.google.com/document/d/1jO1X7GSXWf_R604j5LXinr37ZUf96YVdIXSvjpS_Vyk/edit#heading=h.1afllefcoim8).
