### ISSUE TITLE
Why do we need the given, middle and family name to be separate?

### ISSUE THREAD

**Issue by c00kiemon5ter** [aarc-community/architecture-guidelines#9]
Related to #3 and #4; do we really need to figure out how many strings we can fit in a given name, a middle name or a family name? Are there services that require this separation to justify the time to understand how these attributes are represented in different protocols?

I would argue that having a display name (and/or username) is enough. If someone wants to do further processing to disassemble the display name into a given/middle/family name, they can apply all the logic they want to successfully do this.

What's the driver that mandates that we need to provide this information in separate pieces?

**Comment by NicolasLiampotis** [comment]
Regarding the subject's name in displayable form, we propose to always include the `displayName` attribute in SAML or the `name` claim in OIDC. First name and last name information (`givenName` and `sn` in SAML, or `given_name` and `family_name` in OIDC) may also be present, for example, based on the end-user's nationality if the subject represents a physical person.

**Comment by NicolasLiampotis** [comment]
Updated [name attribute definitions](https://docs.google.com/document/d/1jO1X7GSXWf_R604j5LXinr37ZUf96YVdIXSvjpS_Vyk/edit#heading=h.6qgsexa2no35) accordingly
